# Makefile, Author: Robert Bergeron

WARN = -Wall -Wextra -Werror -Wpedantic -Wshadow
# full gcc exec command
C = gcc -g -O0 -std=c11
CWARN = ${C} ${WARN} -fdiagnostics-color=never
CYY = ${C} -Wno-sign-compare
CDEP = gcc -std=c11 -MM ${WARN}
CDBG = ${C} -pg -fsanitize=address
MKFILE = Makefile
DEPFILE = ${MKFILE}.dep
GMAKE = ${MAKE} --no-print-directory
# name of the compiled executable
EXECNAME = badlib
# .c source files
SRC = badllist.c badalist.c
# .h header files
HDR = badllist.h badalist.h badlib.h
# .o object files
OBJ = ${SRC:.c=.o} ${GENSRC:.c=.o}
# .gch some garbage generated by gcc
GCH = ${HDR:=.gch} ${GENHDR:=.gch}
# files generated by GNU Indent
FMT = ${SRC:=~} ${HDR:=~}
# convenient groups
ALLSRC = ${SRC}
ALLHDR = ${HDR}

all : ${DEPFILE} ${EXECNAME}

# TODO(Robert): make this compile a linkable library
${EXECNAME} : ${OBJ}
	${C} -o ${EXECNAME} ${OBJ}

# TODO(Robert): make this compile a debug version of a linkable library
debug : ${OBJ}
	${CDBG} -o ${EXECNAME} ${OBJ}

test : ${OBJ} units.o
	${CDBG} -lcunit -o ${EXECNAME} ${OBJ} units.o

%.o : %.c ${ALLHDR}
	${C} -c $< ${ALLHDR}

clean:
	rm -f ${OBJ} ${GENSRC} ${GENHDR} ${DEPFILE} ${GCH}

spotless: clean
	rm -f ${EXECNAME} ${FMT} *.output *.out

ci: 
	git add ${HDR} ${SRC} ${MKFILE} units.c .gitignore TODO.md

dep: ${ALLSRC} ${ALLHDR} units.c
	${CDEP} ${ALLSRC} units.c >> ${DEPFILE}

indent:
	indent -l80 -nfca -hnl -ncdb -bad -bap -nbc -bbo -nbfda -npsl -br -brs \
	-brf -ce -cdw -lps -saf -sai -saw -pcs -cs -bs -nut -ts4 -i4 -pi4 -ci4 \
	-cli4 -ppi4 -cbi0 -bli0 ${SRC} ${HDR} parser.y

format:
	clang-format --style=Google -i ${SRC} ${HDR} units.c

${DEPFILE} :
	@ touch ${DEPFILE}
	${GMAKE} dep
