# Makefile, Author: Robert Bergeron

WARN = -Wall -Wextra -Werror -Wpedantic -Wshadow
# full gcc exec command
C = gcc -g -O0 -ansi
CWARN = ${C} ${WARN} -fdiagnostics-color=never
CYY = ${C} -Wno-sign-compare
CDEP = gcc -ansi -MM ${WARN}
CDBG = ${C} -pg -fsanitize=address
MKFILE = Makefile
DEPFILE = ${MKFILE}.dep
GMAKE = ${MAKE} --no-print-directory
# name of the compiled executable
EXECNAME = badlib
# .c source files
SRC = badmap.c badllist.c badalist.c
# .h header files
HDR = badmap.h badllist.h badalist.h badlib.h
# library source files
LIBSRC = murmur3.c
# library header files
LIBHDR = murmur3.h
# convenient groups
ALLSRC = ${SRC}
ALLHDR = ${HDR} ${LIBHDR}
# subsystems
SUBSYS = murmur3
# .o object files
OBJ = ${ALLSRC:.c=.o}
# library object files
LIBOBJ = ${LIBSRC:.c=.o}
# .gch some garbage generated by gcc
GCH = ${ALLHDR:=.gch}
# files generated by GNU Indent
FMT = ${SRC:=~} ${HDR:=~}

# vpath directive for sources and headers
vpath %.c murmur3
vpath %.h murmur3

all : ${DEPFILE} ${EXECNAME}

# TODO(Robert): make this compile a linkable library
${EXECNAME} : ${OBJ}
	${C} -o ${EXECNAME} ${OBJ} ${LIBOBJ}

# TODO(Robert): make this compile a debug version of a linkable library
debug : ${OBJ}
	${CDBG} -o ${EXECNAME} ${OBJ} ${LIBOBJ}

test : ${OBJ} ${LIBOBJ} units.o
	${CDBG} -lcunit -o ${EXECNAME} $^

%.o : %.c ${ALLHDR}
	${C} -c $^

clean:
	rm -f ${OBJ} ${LIBOBJ} ${GENSRC} ${GENHDR} ${DEPFILE} ${GCH}

spotless: clean
	rm -f ${EXECNAME} ${FMT} *.output *.out

ci: 
	git add ${HDR} ${SRC} ${MKFILE} units.c .gitignore TODO.md

dep: ${ALLSRC} ${ALLHDR} units.c
	${CDEP} ${ALLSRC} units.c >> ${DEPFILE}

indent:
	indent -l80 -nfca -hnl -ncdb -bad -bap -nbc -bbo -nbfda -npsl -br -brs \
	-brf -ce -cdw -lps -saf -sai -saw -pcs -cs -bs -nut -ts4 -i4 -pi4 -ci4 \
	-cli4 -ppi4 -cbi0 -bli0 ${SRC} ${HDR} parser.y

format:
	clang-format --style=Google -i ${SRC} ${HDR} units.c

${DEPFILE} :
	@ touch ${DEPFILE}
	${GMAKE} dep
